### ISSUE TITLE
Refused to display URL in a frame because it set 'X-Frame-Options' to 'sameorigin'

### ISSUE THREAD

**Issue by minhducsun2002** [9qz/powercord-together#7]
![image](https://user-images.githubusercontent.com/32769878/120106777-a00f4380-c188-11eb-9514-5342cdd6c459.png)
Happens with all activities as when this issue is opened.

**Comment by 9qz** [comment]
weird its working for me, do you have any other plugin that interferes with this?

**Comment by minhducsun2002** [comment]
Weird. I just checked back and it's fixed. Closing this issue. Sorry for disturbing. :disappointed:
